---
# tasks file for ansible-role-jitsi-prosody

- import_tasks: local_facts.yaml

- name: install base packages
  apt:
      pkg:
      - ufw
      - bmon
      - htop
      - vim
      - prosody

- name: configure firewall rules
  ufw:
      rule: "{{ item.rule }}"
      port: "{{ item.port }}"
      proto: "{{ item.proto }}"
  with_items:
      - { rule: 'allow', port: '22', proto: 'tcp' }
      - { rule: 'allow', port: '5222', proto: 'tcp' }
      - { rule: 'allow', port: '5280', proto: 'tcp' }
      - { rule: 'allow', port: '5347', proto: 'tcp' }

- name: set logging
  ufw:
    logging: 'off'

- name: set ufw policy
  ufw:
    state: enabled
    policy: deny

- name: prosody config
  template:
    src: prosody.cfg.lua.j2
    dest: /etc/prosody/prosody.cfg.lua
  notify: restart prosody service

- name: make sure prosody localhost config is absent
  file:
    path: /etc/prosody/conf.d/localhost.cfg.lua
    state: absent

- name: prosody jitsi host config
  template:
    src: prosody-host.cfg.lua.j2
    dest: /etc/prosody/conf.d/{{jitsi_domain}}.cfg.lua
  notify: restart prosody service

- name: generate certificate
  command: prosodyctl cert generate {{jitsi_domain}}
  args:
    creates: /var/lib/prosody/{{ jitsi_domain }}.crt

- name: generate auth certificate
  command: prosodyctl cert generate auth.{{jitsi_domain}}
  args:
    creates: /var/lib/prosody/{{ jitsi_auth_domain }}.crt

- import_tasks: jitsi-repo.yaml

- name: install jitsi-meet-prosody package
  apt:
      name: jitsi-meet-prosody
      state: latest

# https://community.jitsi.org/t/restrict-creation-of-rooms/17328/6
- name: copy mod_muc_restrict_rooms_exec
  copy:
    src: mod_muc_restrict_rooms_exec.lua
    dest: /usr/lib/prosody/modules/

- name: make sure prosody jitsi auto config file is absent
  file:
    path: /etc/prosody/conf.d/ok.cfg.lua
    state: absent
  notify: restart prosody service

- name: enable prosody service
  systemd:
      name: prosody
      enabled: yes

- name: create jicofo user
  command: prosodyctl register {{jicofo_auth_user}} "{{jitsi_auth_domain}}" "{{jicofo_auth_password}}"

- name: create jvb user
  command: prosodyctl register {{jvb_auth_user}} "{{jitsi_auth_domain}}" "{{jvb_auth_password}}"

- name: register focus roster
  command: prosodyctl mod_roster_command subscribe {{jitsi_focus_domain}} {{jicofo_auth_user}}@{{jitsi_auth_domain}}
